Repository swap0506/acroecology-project_, pull requests merged in 2025-08, with the labels that each got.

#29 Update README
  README.md
Labels: documentation, gssoc'25, level 1

#26 FIXED 4 ISSUES
  package-lock.json
  package.json
  src/App.tsx
  src/components/AuthModal.tsx
  src/components/GreenFooter.tsx
  src/components/HomePageHeader.tsx
  src/components/TranslucentHeader.tsx
  src/main.tsx
Labels: bug, enhancement, gssoc'25, level 2

#32 Added Contributing.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc'25, level 1
